language: php

php:
  - 5.6
  - 7.0
  - 7.1
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update -qq

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3.1" --quiet --no-interaction
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - vendor/bin/codeception build
script:
  - vendor/bin/codeception run -vvv